-- MySQL Script generated by MySQL Workbench
-- Mon May 22 20:59:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_mercados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mercados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mercados` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_mercados` ;

-- -----------------------------------------------------
-- Table `db_mercados`.`mercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercados`.`mercado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_mercados`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mercados`.`estoque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `mercado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mercado_id_idx` (`mercado_id` ASC) VISIBLE,
  INDEX `mercado_tipo_idx` (`mercado_id` ASC) VISIBLE,
  CONSTRAINT `mercado_tipo`
    FOREIGN KEY (`mercado_id`)
    REFERENCES `db_mercados`.`mercado` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
